### ISSUE TITLE
invitation link

### ISSUE THREAD

**Issue by Ugurlu81** [ualbany-csi402-s19/tutorials#2]
Hi, 

I have just joined the class so can I have an invitation link? 

This is my email address and username for GitHub: eugurlu@albany.edu, Ugurlu81

Thanks,
Emre Ugurlu

**Comment by Ugurlu81** [comment]
This is my email address and username for GitHub: eugurlu@albany.edu, Ugurlu81

**Comment by znorcross211** [comment]
added
