### ISSUE TITLE
Access Requested, New Student

### ISSUE THREAD

**Issue by donuradu** [ualbany-csi402-s19/tutorials#3]
Hello, I joined the class a few days ago. I was told that a TA can help me get access to the GitHub repository. Thanks!

**Comment by archx0r** [comment]
@Daytona211 can you help please?

Please give Radu a quick go-through about this.

@donuradu: I highly recommend to at least see the TA this afternoon 4pm office hours

**Comment by znorcross211** [comment]
Hello,

So the homework can be accessed by clicking on the homework repository and clicking the link to create your own repository. 

You should be added now. Feel free to email me if you need anything or have any questions
Email: znorcross@albany.edu
